colorsheme=
vault=/home/nahuel/personal/hub/notes/
lang=
zen=

bindings
prefix=
showdefinition=
notefinder=
vaultfinder=
filebrowser=
navegatethroughtabs=
backlinkref=
grep=
cmp_select_next=
cmp_select_prev=
cmp_confirm=
cmp_complete=
search_same_word=
